# Generated by Django 6.0.7 on 2026-07-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_hora_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_con_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
